// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD2xRYA8Yvqx4dCeT1CUx9nodWe5IZeWU',
    appId: '1:74297160874:web:810b4423a4848c0ee54cd3',
    messagingSenderId: '74297160874',
    projectId: 'studify-bba1d',
    authDomain: 'studify-bba1d.firebaseapp.com',
    storageBucket: 'studify-bba1d.firebasestorage.app',
    measurementId: 'G-W7CJQ5YCZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLV1QypBoO234JUxlWz_2xmzjwOJjSY3g',
    appId: '1:74297160874:android:8fe24a3c6468aab9e54cd3',
    messagingSenderId: '74297160874',
    projectId: 'studify-bba1d',
    storageBucket: 'studify-bba1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzcejSwxkVV0eF8xfk7xQIgbuh-BN34kU',
    appId: '1:74297160874:ios:1847ffb220acccace54cd3',
    messagingSenderId: '74297160874',
    projectId: 'studify-bba1d',
    storageBucket: 'studify-bba1d.firebasestorage.app',
    iosBundleId: 'com.example.studify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzcejSwxkVV0eF8xfk7xQIgbuh-BN34kU',
    appId: '1:74297160874:ios:1847ffb220acccace54cd3',
    messagingSenderId: '74297160874',
    projectId: 'studify-bba1d',
    storageBucket: 'studify-bba1d.firebasestorage.app',
    iosBundleId: 'com.example.studify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD2xRYA8Yvqx4dCeT1CUx9nodWe5IZeWU',
    appId: '1:74297160874:web:3e497d918ea4eec7e54cd3',
    messagingSenderId: '74297160874',
    projectId: 'studify-bba1d',
    authDomain: 'studify-bba1d.firebaseapp.com',
    storageBucket: 'studify-bba1d.firebasestorage.app',
    measurementId: 'G-KJS4QMPW7M',
  );
}
